"""MemoryBackend protocol — the swap-out interface for v2.0 alternatives.

ADR 0002.
"""
from __future__ import annotations
from typing import Any, Protocol

from tsukuyomi.core.types import CanonicalRequest


class MemoryBackend(Protocol):
    async def initialize(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def write_request(self, req: CanonicalRequest) -> None: ...
    async def write_event(self, *, organ: str, severity: str, decision: str | None,
                          reason: str | None, request_id: str | None, metadata: dict[str, Any]) -> None: ...
    async def write_audit(self, audit: dict[str, Any]) -> None: ...
    async def write_sandbox_run(self, run: dict[str, Any]) -> None: ...
    async def query_events(self, *, since_iso: str, organ: str | None = None,
                           decision: str | None = None) -> list[dict[str, Any]]: ...
    async def search_full_text(self, query: str, *, table: str = "events_fts") -> list[dict[str, Any]]: ...
